const QUERY_KEY = {
  GET_ALL_STORE: 'GET_ALL_STORE',
  GET_STORE_BY_KEYWORD: 'GET_STORE_BY_KEYWORD',
  ADD_STORE: 'ADD_STORE',
  UPDATE_STORE: 'UPDATE_STORE',
  DEL_STORE: 'DEL_STORE',
  SEARCH: 'SEARCH',
};

export default QUERY_KEY;
